default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  #database: db/development.sqlite3
  database: 'appstore_dev'

test:
  <<: *default
  database: 'appstore_test'

production:
  <<: *default
  database: 'appstore_prod'
